services:
  api-gateway:
    build:
      context: .   # Path to Dockerfile inside api-gateway folder
      dockerfile: Dockerfile    # Name of the Dockerfile (default)
    image: api-gateway:latest   # Name the built image
    container_name: api-gateway
    ports:
      - 4004:4004
    networks:
      - internal

networks:
  internal:
    name: internal
