services:
  postgres:
    image: postgres:latest
    container_name: auth-service-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - 5001:5432
    volumes:
      - D:/Development_Files/db_volumes/auth-service-db:/var/lib/postgresql/data
    networks:
      - internal


  auth-service:
    build:
      context: .   # Path to Dockerfile inside auth-service folder
      dockerfile: Dockerfile     # Name of the Dockerfile (default)
    image: auth-service:latest   # Name the built image
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: E1AgKPVP2BlPDyt62fTpX8Z4uedTYrs+VTWS7FC2MvNnyCgpC7vXHxQC5Fx5FiwPUlkkZUSTQu1C/iDwSjqGdw==
    depends_on:
      - postgres
    # ports:
    #   - 4005:4005
    networks:
      - internal

networks:
  internal:
    name: internal
