### POST request to create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Random Man",
  "email": "random@gmail.com",
  "address": "123 random street",
  "dateOfBirth": "1995-02-01",
  "registeredDate": "2024-11-20"
}
