### POST request to create a new patient entity
POST http://localhost:4000/api/v1/patients
Content-Type: application/json

{
  "name": "Billing Proto Tester",
  "email": "testing_billing_grpc@gmail.com",
  "address": "123 random street",
  "dateOfBirth": "1995-02-01",
  "registeredDate": "2024-11-20"
}
